DROP TABLE JC_REGISTER_HISTORY;
DROP TABLE JC_SCR_FILE;
DROP TABLE JC_FILE_MOVE_DETAIL;
DROP TABLE JC_COMPILE_DETAIL;
DROP TABLE JC_APP_FILE;
DROP TABLE JC_BUILD_UNIT_PATH;
DROP TABLE JC_BUILD_UNIT;
DROP TABLE JC_FUNCTION_LOG;
DROP TABLE JC_SCR;
DROP TABLE JC_APP_PATH;
DROP TABLE JC_APP;
DROP TABLE JC_PROGRAMMER;
DROP TABLE JC_COORDINATOR;

CREATE TABLE JC_APP (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    APP_ID VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPTION NVARCHAR(256),
    PVCS_PROJ_DB VARCHAR(256) NOT NULL,
    PVCS_PROJ_PATH VARCHAR(256),
    CONSTRAINT UC_APP UNIQUE (PVCS_PROJ_DB, PVCS_PROJ_PATH)
);

CREATE TABLE JC_APP_PATH (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_APP_ID INT NOT NULL REFERENCES JC_APP(ID) ON DELETE CASCADE,
    PATH_TYPE INT NOT NULL,
    PATH NVARCHAR(256) NOT NULL
);

CREATE TABLE JC_BUILD_UNIT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_APP_ID INT NOT NULL REFERENCES JC_APP(ID) ON DELETE CASCADE,
    UNIT_ID VARCHAR(256),
    CONSTRAINT UC_BUILD_UNIT UNIQUE (JC_APP_ID, UNIT_ID)
);

CREATE TABLE JC_APP_FILE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_APP_ID INT NOT NULL REFERENCES JC_APP(ID),
    FILE_PATH NVARCHAR(256) NOT NULL,
    FILE_NAME NVARCHAR(256) NOT NULL,
    JC_BUILD_UNIT_ID INT NOT NULL REFERENCES JC_BUILD_UNIT(ID),
    FILE_TYPE INT NOT NULL,
    CHECKOUT TINYINT,
    FILE_DATETIME DATETIME,
    FILE_SIZE BIGINT,
    FILE_MD5 VARCHAR(32),
    LAST_REGISTER_TIME DATETIME NOT NULL,
    LAST_COMPILE_TIME DATETIME,
    DELETED TINYINT DEFAULT 0
);

CREATE TABLE JC_BUILD_UNIT_PATH (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_BUILD_UNIT_ID INT NOT NULL REFERENCES JC_BUILD_UNIT(ID) ON DELETE CASCADE,
    PATH_TYPE INT NOT NULL,
    PATH NVARCHAR(256) NOT NULL
);

CREATE TABLE JC_PROGRAMMER (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TEAM NVARCHAR(32) NOT NULL,
    NAME NVARCHAR(32) NOT NULL,
    PHONE VARCHAR(20),
    MOBILE VARCHAR(20),
    CONSTRAINT UC_PROGRAMMER UNIQUE (TEAM, NAME)
);

CREATE TABLE JC_COORDINATOR (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TEAM NVARCHAR(32) NOT NULL,
    NAME NVARCHAR(32) NOT NULL,
    PHONE VARCHAR(20),
    MOBILE VARCHAR(20),
    CONSTRAINT UC_COORDINATOR UNIQUE (TEAM, NAME)
);

CREATE TABLE JC_SCR (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SCR_NO NVARCHAR(32) NOT NULL UNIQUE,
    JC_APP_ID INT NOT NULL REFERENCES JC_APP(ID),
    CREATE_TIME DATETIME NOT NULL,
    STATUS INT NOT NULL,
    PROCESS_TIME DATETIME NOT NULL,
    JC_COORDINATOR_ID INT NOT NULL REFERENCES JC_COORDINATOR(ID),
    JC_PROGRAMMER_ID INT NOT NULL REFERENCES JC_PROGRAMMER(ID),
    DESCRIPTION NVARCHAR(256),
    REGISTER_COUNT INT NOT NULL,
    DELETED TINYINT DEFAULT 0
);

CREATE TABLE JC_SCR_FILE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_SCR_ID INT NOT NULL REFERENCES JC_SCR(ID),
    FILE_PATH NVARCHAR(256) NOT NULL,
    FILE_NAME NVARCHAR(256) NOT NULL,
    JC_BUILD_UNIT_ID INT NOT NULL REFERENCES JC_BUILD_UNIT(ID),
    FILE_TYPE INT NOT NULL,
    CHECKOUT TINYINT,
    FILE_DATETIME DATETIME,
    FILE_SIZE BIGINT,
    FILE_MD5 VARCHAR(32),
    LAST_REGISTER_TIME DATETIME NOT NULL,
    LAST_COMPILE_TIME DATETIME,
    DELETED TINYINT DEFAULT 0
);

CREATE TABLE JC_REGISTER_HISTORY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_SCR_ID INT NOT NULL REFERENCES JC_SCR(ID),
    REGISTER_COUNT INT NOT NULL,
    JC_SCR_FILE_ID INT NOT NULL REFERENCES JC_SCR_FILE(ID),
    FILE_TYPE INT NOT NULL,
    CHECK_IN TINYINT NOT NULL,
    REGISTER_ACTION INT NOT NULL,
    FILE_DATETIME DATETIME,
    FILE_SIZE BIGINT,
    FILE_MD5 VARCHAR(32),
    REGISTER_TIME DATETIME NOT NULL,
    CONSTRAINT UC_REGISTER_HISTORY UNIQUE (JC_SCR_ID, REGISTER_COUNT, JC_SCR_FILE_ID)
);

CREATE TABLE JC_FUNCTION_LOG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_SCR_ID INT NOT NULL REFERENCES JC_SCR(ID),
    FUNCTION_ID VARCHAR(32),
    MAKER VARCHAR(32),
    CHECKER VARCHAR(32),
    START_TIME DATETIME,
    END_TIME DATETIME
);

CREATE TABLE JC_FILE_MOVE_DETAIL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_FUNCTION_LOG_ID INT NOT NULL REFERENCES JC_FUNCTION_LOG(ID),
    JC_APP_FILE_ID INT NOT NULL REFERENCES JC_APP_FILE(ID),
    TARGET_PATH NVARCHAR(256),
    PROCESS_RESULT INT
);

CREATE TABLE JC_COMPILE_DETAIL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    JC_FUNCTION_LOG_ID INT NOT NULL REFERENCES JC_FUNCTION_LOG(ID),
    JC_APP_FILE_ID INT NOT NULL REFERENCES JC_APP_FILE(ID),
    PROCESS_RESULT INT
);

/****** for Common security test ******/
/****** Object:  Table [dbo].[USERS]    Script Date: 08/12/2011 11:01:31 ******/
CREATE TABLE [dbo].[USERS](
	[UserID] [char](20) NOT NULL,
	[EmpID] [char](20) NULL,
	[Name] [char](50) NULL,
	[Maker] [char](20) NULL,
	[Checker] [char](20) NULL,
	[Telephone] [char](20) NULL,
	[Pswd0] [binary](32) NULL,
	[Pswd1] [binary](32) NULL,
	[Pswd2] [binary](32) NULL,
	[Pswd3] [binary](32) NULL,
	[Pswd4] [binary](32) NULL,
	[Pswd5] [binary](32) NULL,
	[Enable] [tinyint] NULL,
	[Location] [char](12) NULL,
	[Depart] [char](16) NULL,
	[Business] [char](20) NULL,
	[CreateDate] [datetime] NULL,
	[LastLogin] [datetime] NULL,
	[LastUpdate] [datetime] NULL,
	[ErrorLogin] [tinyint] NULL,
	[GrpName] [char](200) NULL,
	[Branch] [char](20) NULL,
	[Action] [char](1) NULL,
	[LastTab] [int] NULL,
	[ApplicationID] [varchar](6) NULL,
	[GEID] [varchar](10) NULL
) ON [PRIMARY];

/****** Object:  Table [dbo].[SEC_USRBASIC]    Script Date: 08/12/2011 11:01:31 ******/
CREATE TABLE [dbo].[SEC_USRBASIC](
	[USR_ID_C] [varchar](20) NULL,
	[USR_PWD_C] [varbinary](32) NULL
) ON [PRIMARY];

/****** Object:  Table [dbo].[PCAP]    Script Date: 08/12/2011 11:01:31 ******/
CREATE TABLE [dbo].[PCAP](
	[SeqNo] [int] NOT NULL,
	[SvrName] [varchar](20) NULL,
	[DBName] [varchar](20) NULL,
	[UsrName] [varchar](20) NULL,
	[DBID] [varbinary](40) NULL,
	[OleProvider] [varchar](15) NULL,
	[Passync] [tinyint] NULL
) ON [PRIMARY];

/****** Object:  Table [dbo].[FUNCLIST]    Script Date: 08/12/2011 11:01:31 ******/
CREATE TABLE [dbo].[FUNCLIST](
	[FuncCode] [char](15) NOT NULL,
	[FuncDesc] [char](60) NOT NULL,
	[MajorSysCode] [char](4) NOT NULL,
	[TabNo] [int] NOT NULL,
	[ProgPath] [char](60) NOT NULL,
	[MakerID] [char](20) NOT NULL,
	[MakerDate] [char](20) NOT NULL,
	[GrpAdmin] [bit] NOT NULL,
	[GrpUserMgr] [bit] NOT NULL,
	[Grp_Maker] [bit] NOT NULL,
	[Grp_Checker] [bit] NOT NULL,
	[QM_REVIEWER] [bit] NOT NULL,
	[SF] [bit] NOT NULL,
	[CCP] [bit] NOT NULL,
	[CIM] [bit] NOT NULL,
	[CIM1] [bit] NOT NULL,
	[CIM2] [bit] NOT NULL,
	[CIM3] [bit] NOT NULL,
	[CREDIT_CYCLE] [bit] NOT NULL,
	[DATA_CENTER] [bit] NOT NULL,
	[EM_CCI] [bit] NOT NULL,
	[EM_M] [bit] NOT NULL,
	[EM_C] [bit] NOT NULL,
	[EM_I] [bit] NOT NULL,
	[FM] [bit] NOT NULL,
	[INV_ADM] [bit] NOT NULL,
	[QM_SA] [bit] NOT NULL,
	[INS_M] [bit] NOT NULL,
	[INS_C] [bit] NOT NULL,
	[CCP_C] [bit] NOT NULL,
	[Appr_User] [bit] NOT NULL,
	[Appr_Staff] [bit] NOT NULL,
	[BCI] [bit] NOT NULL,
	[APD] [bit] NOT NULL,
	[EM_Q] [bit] NOT NULL,
	[SCB_M] [bit] NOT NULL,
	[SCB_C] [bit] NOT NULL,
	[WORKOUT_HEAD] [bit] NOT NULL,
	[OREO] [bit] NOT NULL,
	[RMS_Admin] [bit] NOT NULL,
	[TCB_HOLIDAY4TPE] [bit] NOT NULL,
	[KHB_HOLIDAY4TPE] [bit] NOT NULL,
	[GSS_M] [bit] NOT NULL,
	[GSS_C] [bit] NOT NULL,
	[TPD] [bit] NOT NULL,
	[CIM_IPS] [bit] NOT NULL,
	[UPMCHECKER] [bit] NOT NULL,
	[FM_IR_INQ] [bit] NOT NULL,
	[FM_OR_MKR] [bit] NOT NULL,
	[FM_OR_CKR] [bit] NOT NULL,
	[AM_Maker] [bit] NOT NULL,
	[AM_Checker] [bit] NOT NULL,
	[LTP_M] [bit] NOT NULL,
	[LTP_C] [bit] NOT NULL,
	[ML_HYB] [bit] NOT NULL,
	[ML_HCB] [bit] NOT NULL,
	[ML_PCB] [bit] NOT NULL,
	[ML_TM] [bit] NOT NULL,
	[ML_RM] [bit] NOT NULL,
	[ML_APD] [bit] NOT NULL,
	[ML_BPA] [bit] NOT NULL,
	[ML_MKT] [bit] NOT NULL,
	[ADM_Maker] [bit] NOT NULL,
	[AM_BSP_M] [bit] NOT NULL,
	[AM_BSP_C] [bit] NOT NULL,
	[AMD_TAX_CHECKER] [bit] NOT NULL,
	[PL_PROC] [bit] NOT NULL,
	[FMD_FISC] [bit] NOT NULL,
	[AMD_PA_TAX_M] [bit] NOT NULL,
	[ML_S] [bit] NOT NULL,
	[ML_SH] [bit] NOT NULL,
	[ML_MGT] [bit] NOT NULL,
	[FM_INV_MKR] [bit] NOT NULL,
	[FM_INV_CKR] [bit] NOT NULL,
	[LIB] [bit] NOT NULL,
	[ML_APD_C] [bit] NOT NULL,
	[AM_M2] [bit] NOT NULL,
	[AM_C2] [bit] NOT NULL,
	[BSG_C] [bit] NOT NULL,
	[BSG_M] [bit] NOT NULL,
	[Dummy] [bit] NOT NULL,
	[KHB_GDB_M] [bit] NOT NULL,
	[TCB_JGB_M] [bit] NOT NULL,
	[MLB_M] [bit] NOT NULL,
	[KHB_GDB_C] [bit] NOT NULL,
	[TCB_JGB_C] [bit] NOT NULL,
	[MLB_C] [bit] NOT NULL,
	[HYB_C] [bit] NOT NULL,
	[HYB_M] [bit] NOT NULL,
	[ML_YHB] [bit] NOT NULL,
	[FA_Maker] [bit] NOT NULL,
	[FA_Checker] [bit] NOT NULL,
	[AM] [bit] NOT NULL,
	[AM1] [bit] NOT NULL
) ON [PRIMARY];

/****** Object:  Table [dbo].[FUNCLOG]    Script Date: 08/12/2011 11:01:31 ******/
CREATE TABLE [dbo].[FUNCLOG](
	[UserID] [char](20) NOT NULL,
	[FuncCode] [char](15) NOT NULL,
	[InDate] [smalldatetime] NOT NULL,
	[InTime] [char](8) NOT NULL,
	[OutDate] [smalldatetime] NULL,
	[OutTime] [char](8) NULL,
	[PrtFlag] [bit] NOT NULL
) ON [PRIMARY];
/****** for Common security test END ******/
