DROP TABLE JC_PROGRAMMER;

CREATE TABLE JC_PROGRAMMER (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TEAM NVARCHAR(32) NOT NULL,
    NAME NVARCHAR(32) NOT NULL,
    PHONE VARCHAR(20),
    MOBILE VARCHAR(20),
    CONSTRAINT UC_PROGRAMMER UNIQUE (TEAM, NAME)
);
