INSERT INTO JC_PROGRAMMER (TEAM, NAME, PHONE, MOBILE) VALUES ('IISI', 'Java', '12345678', '0935123456');
INSERT INTO JC_PROGRAMMER (TEAM, NAME, PHONE, MOBILE) VALUES ('IISI', 'Ruby', '11111111', '0935111111');

INSERT INTO JC_APP (APP_ID, DESCRIPTION, APP_BASE_PATH, PVCS_PROJ_DB) VALUES ('CDIC', '中央存保轉檔', '\\FileServer\Project\CDIC', 'CDIC');
INSERT INTO JC_APP (APP_ID, DESCRIPTION, APP_BASE_PATH, PVCS_PROJ_DB) VALUES ('SDB', '保管箱', '\\FileServer\Project\SDB', 'SDB');

INSERT INTO JC_BUILD_UNIT (JC_APP_ID, UNIT_ID) VALUES (1, 'CLIENT');
INSERT INTO JC_BUILD_UNIT (JC_APP_ID, UNIT_ID) VALUES (1, 'SERVER');
INSERT INTO JC_BUILD_UNIT (JC_APP_ID, UNIT_ID) VALUES (1, 'WRAPPER');

INSERT INTO JC_BUILD_UNIT_PATH (JC_BUILD_UNIT_ID, PATH_TYPE, PATH) VALUES (1, 0, '\\QA\Project\CDIC\source\client');
INSERT INTO JC_BUILD_UNIT_PATH (JC_BUILD_UNIT_ID, PATH_TYPE, PATH) VALUES (1, 1, '\\QA\Project\CDIC\execution\client');
INSERT INTO JC_BUILD_UNIT_PATH (JC_BUILD_UNIT_ID, PATH_TYPE, PATH) VALUES (1, 2, '\\QA\Project\CDIC\backup\client');
INSERT INTO JC_BUILD_UNIT_PATH (JC_BUILD_UNIT_ID, PATH_TYPE, PATH) VALUES (1, 3, '\\PROD1\Project\CDIC\source\client');
INSERT INTO JC_BUILD_UNIT_PATH (JC_BUILD_UNIT_ID, PATH_TYPE, PATH) VALUES (1, 3, '\\PROD2\Project\CDIC\source\client');
INSERT INTO JC_BUILD_UNIT_PATH (JC_BUILD_UNIT_ID, PATH_TYPE, PATH) VALUES (1, 4, '\\PROD1\Project\CDIC\execution\client');
INSERT INTO JC_BUILD_UNIT_PATH (JC_BUILD_UNIT_ID, PATH_TYPE, PATH) VALUES (1, 4, '\\PROD2\Project\CDIC\execution\client');
