INSERT INTO JC_PROGRAMMER (TEAM, NAME, PHONE, MOBILE) VALUES ('IISI', 'Java', '12345678', '0935123456');
INSERT INTO JC_PROGRAMMER (TEAM, NAME, PHONE, MOBILE) VALUES ('IISI', 'Ruby', '11111111', '0935111111');

INSERT INTO JC_APP (APP_ID, DESCRIPTION, PVCS_PROJ_DB) VALUES ('CDIC', '中央存保轉檔', 'CDIC');
INSERT INTO JC_APP (APP_ID, DESCRIPTION, PVCS_PROJ_DB) VALUES ('SDB', '保管箱', 'SDB');

INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 0, '\\QA\Project\CDIC\source');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 1, '\\QA\Project\CDIC\execution');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 2, '\\QA\Project\CDIC\backup');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 3, '\\PROD1\Project\CDIC\source');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 3, '\\PROD2\Project\CDIC\source');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 4, '\\PROD1\Project\CDIC\execution');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 4, '\\PROD2\Project\CDIC\execution');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (1, 5, '\\FileServer\Project\CDIC');

INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (2, 0, '\\QA\Project\SDB\source');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (2, 1, '\\QA\Project\SDB\execution');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (2, 2, '\\QA\Project\SDB\backup');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (2, 3, '\\PROD1\Project\SDB\source');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (2, 4, '\\PROD1\Project\SDB\execution');
INSERT INTO JC_APP_PATH (JC_APP_ID, PATH_TYPE, PATH) VALUES (2, 5, '\\FileServer\Project\SDB');

INSERT INTO JC_BUILD_UNIT (JC_APP_ID, UNIT_ID) VALUES (1, 'CLIENT');
INSERT INTO JC_BUILD_UNIT (JC_APP_ID, UNIT_ID) VALUES (1, 'SERVER');
INSERT INTO JC_BUILD_UNIT (JC_APP_ID, UNIT_ID) VALUES (1, 'WRAPPER');
